config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :users

  get 'statistics/activity/:id' => 'statistics#show', :defaults => { :format => 'json' }
  get 'statistics/user/:year' => 'statistics#index', :defaults => { :format => 'json' }
  get 'register' => 'users#new'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence:true, length: { minimum: 4 }, allow_nil: true
  has_secure_password

  has_many :activities, :dependent => :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def max_heart_rate
    185
  end

  def min_heart_rate
    54
  end

  def lactate_threshold
    168
  end

  def distance_total_km date_params = {}
    distance = 0
    activities = activities_for_time_span date_params
    activities.each do |activity|
      distance += activity.distance_km
    end
    distance
  end

  def activities_total date_params = {}
    activities = activities_for_time_span date_params
    activities.count
  end

  def activities_for_time_span date_params = {}
    year = date_params[:year]
    month = date_params[:month]
    case
     when (year.present? && month.nil?) then self.activities.by_year(year)
     when (year.nil? && month.present?) then self.activities.by_month(month)
     when (year.present? && month.present?) then self.activities.by_year_and_month(year, month)
     when (year.nil? && month.nil?) then self.activities.all
     else []
    end
  end

  def admin?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CalendarHelper
  load_and_authorize_resource

  def show
    @user = User.find(params[:id])
    @activities = @user.activities
    @activities_by_date = @user.activities.group_by { |a| a[:start_time].to_date }
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Cycling on Rails App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Id
      %th Name
      %th Email
      %th Activities Total
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.name
        %td= user.email
        %td= user.activities.count
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up

%row
  .col-md-6.col-md-offset-3
    = render 'shared/error_messages'
    = form_for(@user) do |f|
      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.email_field :email, class: 'form-control'

      = f.label :password
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'

      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- this_month = Date.today.month
- this_year = Date.today.year

.row
  .col-sm-1
    .btn-group-vertical
      .btn#tlf TLF
      .btn#add ADD
      .btn#wtf WTF
  .col-sm-10.chart-container
    #dashboard-chart
  .col-sm-1
    .btn-group-vertical
      .btn#standard_range standard
      .btn#last_three_months last 3 months
      .btn#this_month this month
      .btn#last_month last month
      .btn#this_year this year
      .btn#last_year last year
.row
  .col-sm-12
    #activities
      %h2
        .prev_month= link_to "<", user_path(date: @date.prev_month)
        = @date.strftime("%B %Y")
        .next_month= link_to ">", user_path(date: @date.next_month)
      = calendar @date do |date|
        = date.day
        - if @activities_by_date[date]
          %ul
            - @activities_by_date[date].each do |activity|
              %li
                = link_to activity, class: "activity activity-#{activity.id}", :data => { :id => "#{activity.id}"} do
                  = "#{activity.sport} #{number_with_precision activity.distance_km, precision: 1} km"
                  = stars_by_trimp activity.trimp
                  -#= link_to edit_activity_path(activity), class: 'btn' do
                  -#  %span.glyphicon.glyphicon-edit
                = link_to activity, class: 'btn', :method => :delete, :data => { :confirm => 'Are you sure?' } do
                  %span.glyphicon.glyphicon-trash