config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :users

  get 'statistics/activity/:id' => 'statistics#show', :defaults => { :format => 'json' }
  get 'statistics/user/:year' => 'statistics#index', :defaults => { :format => 'json' }
  get 'register' => 'users#new'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :laps, :dependent => :destroy

  scope :this_week, -> { where(:start_time => Time.now.beginning_of_week..Time.now.end_of_week) }
  scope :this_month, -> { where(:start_time => Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :this_year, -> { where(:start_time => Time.now.beginning_of_year..Time.now.end_of_year) }
  scope :by_month, ->(month){ where(:start_time => Date.new(Date.now.year, month, 1).beginning_of_month..Date.new(Date.now.year,month,1).end_of_month) }
  scope :by_year, ->(year){ where(:start_time => Date.new(year, 1, 1).beginning_of_year..Date.new(year,1,1).end_of_year) }
  scope :by_year_and_month, ->(year, month){ where(:start_time => Date.new(year, month, 1).beginning_of_month..Date.new(year,month,1).end_of_month) }

  def avghr_bpm
    self.avg_heart_rate
  end

  def duration_s
    duration_seconds = 0
    self.laps.each do |lap|
      duration_seconds += lap.total_time_seconds
    end
    duration_seconds.to_f
  end

  def duration_min
    (duration_s / 60).to_f
  end

  def duration_h
    (duration_min / 60).to_f
  end

  def duration_hours # returns a string value for views
    "#{(duration_min / 60).to_i}:#{(duration_min % 60).to_i} h"
  end

  def distance_km
    (distance_m/1000).to_f
  end

  def distance_mi
    ((distance_m/1000)/1.609344).to_f
  end

  def intensity
    self.avg_heart_rate.fdiv(self.user.lactate_threshold) / 100 * 90
  end

  def hf_per_rest
    (self.avg_heart_rate - self.user.min_heart_rate).fdiv(self.user.max_heart_rate - self.user.min_heart_rate)
  end

  def calculate_trimp
    rpe = 7 #cycling
    a = 0.64
    b = 1.92
    #a, b: Faktoren (für Männer: a = 0.64, b = 1.92 - für Frauen: a = 0.86, b = 1.67)
    duration_min * (hf_per_rest * a * (Math::E ** (b * hf_per_rest))) * rpe.fdiv(10)
  end

  def trimp_imp
    trimp
  end

  ### The following is all about parsing/importing the tcx/xml ###
  def save_with_all_properties data
    @heart_rate_array = []
    self.laps = []
    self.distance_m = 0
    self.sport = data['Activities']['Activity']['Sport']
    self.activity_id = data['Activities']['Activity']['Id']
    self[:start_time] ||= DateTime.parse(data['Activities']['Activity']['Id'])
    if data['Activities']['Activity']['Lap'].class == Array
      data['Activities']['Activity']['Lap'].each do |lap|
        parse_lap lap
      end
    else
      parse_lap data['Activities']['Activity']['Lap']
    end
    self.avg_heart_rate = @heart_rate_array.sum / @heart_rate_array.count
    self.trimp = calculate_trimp
  end

  def parse_lap lap
    tmp_lap = Lap.new
    tmp_lap[:start_time] = DateTime.parse(lap['StartTime'])
    tmp_lap[:total_time_seconds] = lap['TotalTimeSeconds'].to_f
    tmp_lap[:distance_meters] = lap['DistanceMeters']
    tmp_lap[:calories] = lap['Calories']
    tmp_lap[:cadence] = lap['Cadence']
    tmp_lap[:average_heart_rate_bpm] = lap['AverageHeartRateBpm']
    tmp_lap[:maximum_heart_rate_bpm] = lap['MaximumHeartRateBpm']
    tmp_lap[:maximum_speed] = lap['MaximumSpeed']
    tmp_lap[:intensity] = lap['Intensity']
    tmp_lap[:trigger_method] = lap['TriggerMethod']
    self.distance_m += tmp_lap[:distance_meters]
    tmp_track = Track.new
    lap['Track']['Trackpoint'].each do |trackpoint|
      puts trackpoint['DistanceMeters']
      tmp_track_point = TrackPoint.new
      tmp_track_point[:time] = trackpoint['Time']
      tmp_track_point[:altitude_meters] = trackpoint['AltitudeMeters']
      tmp_track_point[:distance_meters] = trackpoint['DistanceMeters']
      tmp_track_point[:heart_rate_bpm] = trackpoint['HeartRateBpm'] ? trackpoint['HeartRateBpm']['Value'] : 0
      @heart_rate_array << tmp_track_point[:heart_rate_bpm].to_i
      tmp_track_point[:sensor_state] = trackpoint['SensorState']
      if trackpoint[:Position].present?
        tmp_position = Position.new
        tmp_position[:latitude_degrees] = trackpoint['Position']['LatitudeDegrees']
        tmp_position[:longitude_degrees] = trackpoint['Position']['LongitudeDegrees']
        tmp_track_point.position = tmp_position
      end
      tmp_track.track_points << tmp_track_point
    end
    tmp_lap.track = tmp_track
    self.laps << tmp_lap
    # parse_extension TODO
    # parse_training ['Activities']['Activity']['Training'] TODO
    # parse_creator ['Activities']['Activity']['Creator'] TODO
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.build(activity_params)
    @activity.save_with_all_properties params[:TrainingCenterDatabase]
    respond_to do |format|
      if @activity.save!
        format.xml { render nil, status: :ok }
        format.json { render :show, status: :created, location: @activity }
      else
        format.xml { render xml: @activity.errors, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.permit(:user_id, "TrainingCenterDatabase", :activity)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :tcx
    = f.file_field :tcx
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %thead
    %tr
      %th User
      %th Sport
      %th Id
      %th
      %th
      %th

  %tbody
    - @activities.each do |activity|
      %tr
        %td= activity.user.name if activity.user.present?
        %td= activity.sport
        %td= activity.activity_id
        %td= link_to 'Show', activity
        %td= link_to 'Edit', edit_activity_path(activity)
        %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%h1= @activity.user.name
%p
  %b Sport:
  = @activity.sport
%p
  %b Average Heart Rate:
  = @activity.avg_heart_rate
%p
  %b Start Time:
  = @activity.start_time

%p
  %b Total Distance(km):
  = @activity.distance_km

%p
  %b Duration (minutes):
  = @activity.duration_min

%p
  %b Intensity
  = @activity.intensity

%table
  %tr
    %th Start Time
    %th Avg Heart Rate
    %th Distance (m)
  - @activity.laps.each do |lap|
    %tr
      %td= lap.start_time
      %td= lap.average_heart_rate_bpm
      %td= lap.distance_meters
= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Delete', @activity, class: 'btn', :method => :delete, :data => { :confirm => 'Are you sure?' }
\|
= link_to 'Back', activities_path