config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :users

  get 'statistics/activity/:id' => 'statistics#show', :defaults => { :format => 'json' }
  get 'statistics/user/:year' => 'statistics#index', :defaults => { :format => 'json' }
  get 'register' => 'users#new'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new'
end

app/views/layouts/_flash.html.haml
- flash.each do |message_type, message|
  .alert{ class: "alert-#{ message_type }"}= message

app/views/layouts/_footer.html.haml
%footer.navbar.navbar-bottom
  .navbar-inner
    .container
      %nav
        .nav.pull-right
          -#- if logged_in?
          -#  - if current_user.role == 'admin'
          -#    .btn-group
          -#      %a.btn.btn-inverse.dropdown-toggle{ data: {toggle: "dropdown"}, href: '#'}
          -#        Admin
          -#        %span.caret
          -#      %ul.dropdown-menu
          -#        %li= link_to "Benutzer", users_path
          -#  .btn-group
          -#    -if can? :show, current_user
          -#      = link_to user_path(current_user), class: "btn" do
          -#        %i.icon-user
          -#    = link_to logout_path, method: "delete", class: "btn" do
          -#      %i.icon-eject
          -#
          -#- else
          .btn-group
            = link_to "Help", help_path, class: "btn"
            = link_to "About", about_path, class: "btn"
            -#= link_to "Registrieren", register_path, class: "btn btn-success"

app/views/layouts/_navigation.html.haml
-#%header.navbar.navbar-top.navbar-blue
-#  .navbar-inner
-#    .container
-#      %nav
-#        .nav.pull-right
-#          - if logged_in?
-#            -#- if current_user.role == 'admin'
-#            -#  .btn-group
-#            -#    %a.btn.btn-inverse.dropdown-toggle{ data: {toggle: "dropdown"}, href: '#'}
-#            -#      Admin
-#            -#      %span.caret
-#            -#    %ul.dropdown-menu
-#            -#      %li= link_to "Benutzer", users_path
-#            .btn-group
-#              -#-if can? :show, current_user
-#              = link_to users_path, class: "btn" do
-#                %span.glyphicon.glyphicon-list
-#              = link_to current_user, class: "btn" do
-#                %span.glyphicon.glyphicon-user
-#              %a.btn.btn-file
-#                %span.upload.glyphicon.glyphicon-upload
-#                -#%input#fileChooser.btn{ type: "file" }
-#                %input#fileChooser{ type: "file", multiple: "multiple" }
-#              = link_to logout_path, method: "delete", class: "btn" do
-#                %span.glyphicon.glyphicon-log-out
-#
-#          - else
-#            .btn-group
-#              = link_to "Register", register_path, class: "btn"
-#              = link_to login_path, class: "btn" do
-#                %span.glyphicon.glyphicon-log-in
.mdl-layout.mdl-js-layout.mdl-layout--fixed-header
  %header.mdl-layout__header
    .mdl-layout__header-row
      %span.mdl-layout-title Cycling
      .mdl-layout-spacer
      %nav.mdl-navigation.mdl-layout--large-screen-only
        - if logged_in?
          -#- if current_user.role == 'admin'
          -#  .btn-group
          -#    %a.btn.btn-inverse.dropdown-toggle{ data: {toggle: "dropdown"}, href: '#'}
          -#      Admin
          -#      %span.caret
          -#    %ul.dropdown-menu
          -#      %li= link_to "Benutzer", users_path
          -#-if can? :show, current_user
          = link_to users_path, class: "btn" do
            %span.glyphicon.glyphicon-list
          = link_to current_user, class: "btn" do
            %span.glyphicon.glyphicon-user
          %a.btn.btn-file
            %span.upload.glyphicon.glyphicon-upload
            -#%input#fileChooser.btn{ type: "file" }
            %input#fileChooser{ type: "file", multiple: "multiple" }
          = link_to logout_path, method: "delete", class: "btn" do
            %span.glyphicon.glyphicon-log-out

        - else
          = link_to "Register", register_path, class: "btn"
          = link_to login_path, class: "btn" do
            %span.glyphicon.glyphicon-log-in

-#  <div class="mdl-layout__drawer">
-#    <span class="mdl-layout-title">Title</span>
-#    <nav class="mdl-navigation">
-#      <a class="mdl-navigation__link" href="">Link</a>
-#      <a class="mdl-navigation__link" href="">Link</a>
-#      <a class="mdl-navigation__link" href="">Link</a>
-#      <a class="mdl-navigation__link" href="">Link</a>
-#    </nav>
-#  </div>
-#  <main class="mdl-layout__content">
-#    <div class="page-content"><!-- Your content goes here --></div>
-#  </main>
-#</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<div class="blurdiv">
    <h1>uploading files!</h1>
  <h2>files left: <span class="number_of_files"></span></h2>
</div>
<%= render 'layouts/navigation' %>
<%= render 'layouts/flash' %>
<div class="content container">
    <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>